CHOOSING_TYPE = "choosing_type"
CHOOSING_GRADES = "choosing_grades"
ENTERING_DESCRIPTION = "entering_description"
WAITING_LOCATION = "waiting_location"
WAITING_PHOTOS = "waiting_photos"
ENTERING_COMMENT = "entering_comment"
CONFIRMING = "confirming"
